-- This file is generated by program!
-- Don't change it manaully.
-- Created at: Fri Mar 25 11:40:00 2016


local StringTable =
{	["helloTxt"] = "Hello World",
	["noTxt"] = "No",
	["okTxt"] = "OK",
}

function StringTable.GetText(key, ...)
	return string.format(StringTable[key], ...);
end

function StringTable.GetTempText(key, ...)
	return string.format(key, ...);
end

return StringTable