-- This file is generated by program!
-- Don't change it manaully.
-- Created at: Mon Mar 28 06:16:09 2016


local string_table =
{	["helloTxt"] = "你好",
	["noTxt"] = "取消",
	["okTxt"] = "确定",
}

function string_table.get_text(key, ...)
	return string.format(string_table[key], ...);
end

function string_table.get_temp_text(key, ...)
	return string.format(key, ...);
end

return string_table